CREATE TABLE users(
	id TEXT PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16)))),
	emai TEXT UNIQUE NOT NULL,
	username TEXT UNIQUE NOT NULL,
	password_hash TEXT UNIQUE NOT NULL,
	created_at TIMESTAMP NOT NUL DEFAULT CURRENT_TIMESTAMP,
	last_login TIMESTAMP
);


CREATE TABLE refresh_tokens(
	id TEXT PRIMARY KEY DEFAULT (LOWER(HEX(RANDOMBLOB(16))))
	user_id TEXT NULL,
	token TEXT UNIQUE NOT NULL,
	expires_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	revoked INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEU (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token)
